//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameProject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerScore
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Score { get; set; }
    }
}
